spring:
  profiles:
    active: Test
---
spring:
  config:
    activate:
      on-profile: Local
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: General
  datasource:
    username: postgres
    url: jdbc:postgresql://192.168.0.0:5432/postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: Test
  datasource:
    username: root
    url: jdbc:h2:mem:testdb
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect